# -*- coding: utf-8 -*-
"""M23MA2003_prob1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E0FUxqEOJKqFMxjBC0-VFBuqBGPoqRtQ

##Task1
"""

import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from wordcloud import WordCloud
import matplotlib.pyplot as plt

#Tokenizer download
nltk.download('punkt')
nltk.download('punkt_tab')

def preprocess(text):
  text = re.sub(r'\\',' ',text)#remove tags
  text = re.sub(r'\s+',' ',text) # remove newline and tags
  text = re.sub(r'[^\x00-\x7F]+',' ',text) #remove non-ASCII(filter English only)
  text = text.lower() # Lower-casing
  text = re.sub(r'[^a-z\s]','',text) # remove non textual content(numbers) ,keep only alphabets,letters ans space
  tokens = word_tokenize(text) #Tokenize
  return tokens

# Read uploaded file
with open("Corpus.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

raw_text

#treating paragraphs as individual doc for the corpus
raw = raw_text.split('\n\n')
clean_corp = [preprocess(d) for d in raw if d.strip()]

corpus = [d for d in clean_corp if d]

corpus

total_docs = len(corpus)
tokens = [t for d in corpus for t in d]
total_tokens = len(tokens)
vocab_size = len(set(tokens))

print('Dataset Statistics')
print(f"Total Documents : {total_docs}")
print(f"Total Tokens : {total_tokens}")
print(f"Vocabulary Size : {vocab_size}")

#Save cleaned corpus
with open("Cleaned_corpus.txt","w",encoding="utf-8") as f:
    for line in corpus:
        f.write(" ".join(line)+"\n")
print("Cleaned data saved to 'Cleaned_corpus.txt")

"""Word Cloud"""

full_text_string = " ".join(tokens)
wordcloud = WordCloud(width=800, height=400, background_color='white',
                      colormap='viridis', max_words=100).generate(full_text_string)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("IIT Jodhpur Corpus Word Cloud")
plt.show()

"""##Task 2"""

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from collections import Counter
import numpy as np

!pip install gensim
from gensim.models import Word2Vec

# Vocabulary set up
def load_corpus(path,mf = 2):
  with open(path,'r',encoding='utf-8') as f:
    tokens = f.read().split() # Reads file and splits into a list of all words
  #Count frequencies and filter rare words
  rc = Counter(tokens)
  fil_tokens = [w for w in tokens if rc[w] > mf]
  return fil_tokens

path = "/content/Cleaned_corpus.txt"
corpus = load_corpus(path,mf=2)

corpus

#Vocabulary
vocab = list(set(corpus))
# paddinfg token for CBow
vocab.append("<PAD>")

word_to_idx = {w:i for i,w in enumerate(vocab)}
idx_to_word = {i:w for i,w in enumerate(vocab)}

vocab_size = len(vocab)
pad_idx = word_to_idx["<PAD>"]

print(f"Corpus size: {len(corpus)} words")
print(f"Vocabulary size: {vocab_size}")

# Word frequencies excluding <PAD>
word_count = Counter(corpus)
total_words = sum(word_count.values())

#Uniform distribution
uni_dist = np.zeros(vocab_size)
for i in range(vocab_size):
  if idx_to_word[i] != "<PAD>":
    uni_dist[i] = word_count[idx_to_word[i]]/total_words
# P(w) = U(w)^(3/4) / Z
power = 0.75
neg_sample_dist = np.power(uni_dist,power)
neg_sample_dist = neg_sample_dist/np.sum(neg_sample_dist)

#Convert to pytorch tensor
neg_sample_dist_tensor = torch.FloatTensor(neg_sample_dist)

def get_negative_samples(batch_size,num_samples):
  return torch.multinomial(neg_sample_dist_tensor, batch_size * num_samples, replacement=True).view(batch_size, num_samples) # Draws samples based on 3/4 power distribution

def generate_training_data(corpus,window_size,model = "skipgram"):
  data = []
  idx = [word_to_idx[w] for w in corpus]
  for i,center_word in enumerate(idx):
    context_st = max(0,i-window_size)
    context_end = min(len(idx),i+window_size+1)
    context_word = [idx[j] for j in range(context_st,context_end) if j!=i]
    if model == "skipgram":
      for c in context_word:
        data.append((center_word,c))
    elif model == "cbow":
      if len(context_word) < 2*window_size:
        padding = [pad_idx] * (2*window_size-len(context_word))
        context_word.extend(padding)
      data.append((context_word,center_word))

  return data

#Skip-gram
class SkipGramNegSampling(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super(SkipGramNegSampling, self).__init__()
        self.center_embeddings = nn.Embedding(vocab_size, embedding_dim)
        self.outside_embeddings = nn.Embedding(vocab_size, embedding_dim)
        nn.init.uniform_(self.center_embeddings.weight, -0.5/embedding_dim, 0.5/embedding_dim)
        nn.init.zeros_(self.outside_embeddings.weight)

    def forward(self, center_words, context_words, negative_words):
        v_c = self.center_embeddings(center_words)
        u_o = self.outside_embeddings(context_words)
        u_k = self.outside_embeddings(negative_words)

        pos_score = torch.bmm(u_o.unsqueeze(1), v_c.unsqueeze(2)).squeeze()
        neg_score = torch.bmm(u_k, v_c.unsqueeze(2)).squeeze(-1)
        return pos_score, neg_score

#CBow
class CBOWNegSampling(nn.Module):
    def __init__(self, vocab_size, embedding_dim, pad_idx):
        super(CBOWNegSampling, self).__init__()
        # Use padding_idx so the PAD token doesn't affect gradients
        self.context_embeddings = nn.Embedding(vocab_size, embedding_dim, padding_idx=pad_idx)
        self.target_embeddings = nn.Embedding(vocab_size, embedding_dim, padding_idx=pad_idx)

    def forward(self, context_words, center_words, negative_words):
        v_c = self.context_embeddings(context_words).mean(dim=1)
        u_o = self.target_embeddings(center_words)
        u_k = self.target_embeddings(negative_words)

        pos_score = torch.bmm(u_o.unsqueeze(1), v_c.unsqueeze(2)).squeeze()
        neg_score = torch.bmm(u_k, v_c.unsqueeze(2)).squeeze(-1)
        return pos_score, neg_score

#Objective function
def negative_sampling_loss(pos_score, neg_score):
    pos_loss = -F.logsigmoid(pos_score)
    neg_loss = -torch.sum(F.logsigmoid(-neg_score), dim=1)
    return torch.mean(pos_loss + neg_loss)

#Training Loop
def train_word2vec(model_type="skipgram", embed_dim=50, window_size=3, num_neg_samples=5, epochs=3, batch_size=256):
    print(f"\nTraining {model_type.upper()} | Dim: {embed_dim} | Window: {window_size} | NegSamples: {num_neg_samples}")

    data = generate_training_data(corpus, window_size, model_type)

    if model_type == "skipgram":
        model = SkipGramNegSampling(vocab_size, embed_dim)
    else:
        model = CBOWNegSampling(vocab_size, embed_dim, pad_idx)

    # FIXED: Standard Adam Optimizer to prevent crashes
    optimizer = optim.Adam(model.parameters(), lr=0.01)



    for epoch in range(epochs):
        total_loss = 0
        np.random.shuffle(data)

        for i in range(0, len(data), batch_size):
            batch = data[i:i+batch_size]

            if model_type == "skipgram":
                centers = torch.tensor([b[0] for b in batch], dtype=torch.long)
                contexts = torch.tensor([b[1] for b in batch], dtype=torch.long)
                neg_samples = get_negative_samples(len(batch), num_neg_samples)

                optimizer.zero_grad()
                pos_score, neg_score = model(centers, contexts, neg_samples)

            else: # CBOW
                contexts = torch.tensor([b[0] for b in batch], dtype=torch.long)
                centers = torch.tensor([b[1] for b in batch], dtype=torch.long)
                neg_samples = get_negative_samples(len(batch), num_neg_samples)

                optimizer.zero_grad()
                pos_score, neg_score = model(contexts, centers, neg_samples)

            loss = negative_sampling_loss(pos_score, neg_score)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"  Epoch {epoch+1}/{epochs}, Loss: {total_loss/(len(data)/batch_size):.4f}")

    return model



"""Skipgram"""

model_sk1 = train_word2vec("skipgram",embed_dim=50,window_size=3,num_neg_samples=5,epochs=10,batch_size=128)

model_sk2 = train_word2vec("skipgram",embed_dim=80,window_size=2,num_neg_samples=5,epochs=10,batch_size=128)

model_sk3 = train_word2vec("skipgram",embed_dim=100,window_size=2,num_neg_samples=5,epochs=10,batch_size=128)

model_sk4 = train_word2vec("skipgram",embed_dim=150,window_size=3,num_neg_samples=10,epochs=10,batch_size=128)

model_sk5 = train_word2vec("skipgram",embed_dim=80,window_size=1,num_neg_samples=5,epochs=10,batch_size=256)

model_sk6 = train_word2vec("skipgram",embed_dim=30,window_size=2,num_neg_samples=10,epochs=50,batch_size=256)

model_sk7 = train_word2vec("skipgram",embed_dim=50,window_size=2,num_neg_samples=15,epochs=50,batch_size=128)

Cbow_model1= train_word2vec("cbow",embed_dim=50,window_size=2,num_neg_samples=5,epochs=30,batch_size=128)

Cbow_model2= train_word2vec("cbow",embed_dim=20,window_size=2,num_neg_samples=5,epochs=30,batch_size=128)

Cbow_model3= train_word2vec("cbow",embed_dim=50,window_size=2,num_neg_samples=15,epochs=50,batch_size=256)

# Gensim Baseline Model
gen_corpus = [corpus]
gensim_cbow = Word2Vec(sentences=gen_corpus, vector_size=50, window=2, negative=5, sg=0, min_count=2, epochs=50)

gensim_sg = Word2Vec(sentences=gen_corpus, vector_size=50, window=2, negative=5, sg=1, min_count=2, epochs=30)

"""##Task 3"""

#Extract weights and normalize for them for cosine similarity
def norm_embed(model,model_type = "skipgram"):
  if model_type == "skipgram":
    embeddings = model.center_embeddings.weight.data.cpu() # Since center word embeddings are primary representation fro skipgrams
  else:
    embeddings = model.target_embeddings.weight.data.cpu() # for cbow target embeddings
  embeddings = F.normalize(embeddings, p=2, dim=1) #Normalize
  return embeddings

model_sk = train_word2vec("skipgram",embed_dim=50,window_size=2,num_neg_samples=5,epochs=50,batch_size=128)

model_cbow = train_word2vec("cbow",embed_dim=50,window_size=2,num_neg_samples=5,epochs=50,batch_size=128)

sg_embeddings = norm_embed(model_sk,"skipgram")
cbow_embeddings = norm_embed(model_cbow,"cbow")

from gensim import topic_coherence
#Cosine Similarity(Nearest Neighbours)
def get_topn_neigh(word,embeddings,word_to_idx,idx_to_word,n=5):
  if word not in word_to_idx:
    return f"Word '{word}' not in vocabulary"
  word_idx = word_to_idx[word]
  word_vec = embeddings[word_idx]

  #Calculate cosine similarity
  s = torch.matmul(embeddings,word_vec)

  #get top N+1 indices
  top_indices = torch.topk(s,n+1).indices.tolist()

  nbd = []
  for i in top_indices :
    #Exclude word itself and padding
    if i!= word_idx and idx_to_word[i] != "<PAD>":
      nbd.append((idx_to_word[i],round(s[i].item(),4)))
      if len(nbd) == n:
        break
  return nbd

"""Instead of exam ,I have taken the word examination as it is present in my vocab and exam is not there in my vocab."""

target = ['research','student','phd','examination']
print("Top 5 nearest neighbour:\n")
for word in target:
  print(f"\nTarget Word : '{word}'")
  print("Skip-gram: ",get_topn_neigh(word,sg_embeddings,word_to_idx,idx_to_word))
  print("CBOW: ",get_topn_neigh(word,cbow_embeddings,word_to_idx,idx_to_word))

#Analogy experiment
def solve_analogy(a,b,c,embeddings,word_to_idx,idx_to_word):
  for w in [a,b,c]:
    if w not in word_to_idx:
      return f"[Word '{w}' not in vocabulary]"

  vec_a = embeddings[word_to_idx[a]]
  vec_b = embeddings[word_to_idx[b]]
  vec_c = embeddings[word_to_idx[b]]

  #Apply analogy
  target_vec= vec_b-vec_a+vec_c
  target_vec = F.normalize(target_vec,p=2,dim=0)

  #Calculate cosine
  s = torch.matmul(embeddings,target_vec)
  top_ind = torch.topk(s,10).indices.tolist()

  for i in top_ind:
    word_guess = idx_to_word[i]
    #Excluding the input words and padding
    if word_guess not in [a,b,c,"<PAD>"]:
      score = s[i].item()
      return f"'{word_guess}' (Score :{score:.4f})"

  return "No valid analogy found"

analogy = [('ug','btech','pg'),('btech','student','phd'),('theory','examination','research')]
for i,j,k in analogy:
  print(f"\nAnalogy: {i}:{j}::{k}:?")
  print("Skip-gram Result:",solve_analogy(i,j,k,sg_embeddings,word_to_idx,idx_to_word))
  print("CBOW Result:",solve_analogy(i,j,k,cbow_embeddings,word_to_idx,idx_to_word))

"""#Task 4"""

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import numpy as np

# Select words to visualize
w_to_viusal = ['research', 'student', 'phd', 'exam','btech', 'mtech', 'ug', 'pg','theory', 'thesis', 'medical', 'engineering','science', 'biology', 'course', 'faculty']

#Filter out the words which are not in vocab
valid_words = [w for w in w_to_viusal if w in word_to_idx]

# pytorch tensors are converted to numpy arr for sklearn
sg_vec = np.array([sg_embeddings[word_to_idx[w]].numpy() for w in valid_words])
cbow_vec = np.array([cbow_embeddings[word_to_idx[w]].numpy() for w in valid_words])

#PCA(dim 2)
pca = PCA(n_components=2)
sg_pca = pca.fit_transform(sg_vec)
cbow_pca = pca.fit_transform(cbow_vec)

# Plot Skip-gram
plt.scatter(sg_pca[:, 0], sg_pca[:, 1])
for i, word in enumerate(valid_words):
    plt.text(sg_pca[i, 0], sg_pca[i, 1], word)
plt.title("Skip-gram PCA")
plt.show()

# Plot CBOW
plt.scatter(cbow_pca[:, 0], cbow_pca[:, 1])
for i, word in enumerate(valid_words):
    plt.text(cbow_pca[i, 0], cbow_pca[i, 1], word)
plt.title("CBOW PCA")
plt.show()